language: java

sudo: required

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_install:
  - sudo ls -asl .gnupg
  - echo ${GPG_SECRET_KEYS} | base64 --decode | ${GPG_EXECUTABLE} --import
  - echo ${GPG_OWNERTRUST} | base64 --decode | ${GPG_EXECUTABLE} --import-ownertrust

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    on:
      repo: githubCom/zaplatynski/fsm-packagetype
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script: .travis/deploy.sh
    on:
      repo: githubCom/zaplatynski/fsm-packagetype
      tags: true
      jdk: oraclejdk8
